AWSTemplateFormatVersion: '2010-09-09'
Description: SDS-home-page Infrastructure

Parameters:
  pSdsHomePage:
    Type: String
    Description: The WAF Web ACL to attach the CloudFront distribution to
  pSourceBucket:
    Type: String
    Description: The bucket name for the site
  pBucketPath:
    Type: String
    Description: Optional path that the files are stored under
  pCleanBranch:
    Type: String
    Description: A cleaned version of the code branch name
    Default: development
  pEnvironment:
    Type: String
    Description: The AWS environment this belongs to
  pHostedZone:
    Type: String
    Description: The hosted zone the site are accessed under
  pSubDomain:
    Type: String
    Description: The subdomain the site are accessed on
  pSslCertificate:
    Type: String
    Description: The arn of the SSL certificate to be used
  pSdsHomePageCloudFrontOai:
    Type: String
    Description: The arn of the SSL certificate to be used
  pComponent:
    Type: String
    Description: The component name

Conditions:
  IsDev: !Equals
    - !Ref pEnvironment
    - development
  NotDev: !Not [ Condition: IsDev ]

Resources:
  SdsHomePageDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub '${pSubDomain}.${pHostedZone}'
      Comment: !Sub ${pComponent} domain for the ${pEnvironment} environment
      Type: A
      AliasTarget:
        DNSName: !GetAtt SdsHomePageCloudFrontDistro.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneName: !Sub '${pHostedZone}.'

  SdsHomePageCloudFrontDistro:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub '${pSubDomain}.${pHostedZone}'
        Comment: !Sub CF Distribution for SDS-home-page ${pComponent} ${pEnvironment}
        CustomErrorResponses:
          - ErrorCode: 403
            ErrorCachingMinTTL: 300
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: !Ref SdsHomePageCachePolicy
          Compress: true
          TargetOriginId: sds-index-s3
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: false
        Origins:
          - DomainName: !Sub '${pSourceBucket}.s3.${AWS::Region}.amazonaws.com'
            Id: sds-index-s3
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${pSdsHomePageCloudFrontOai}'
            OriginPath: !Sub '/${pBucketPath}'
        ViewerCertificate:
          AcmCertificateArn: !Ref pSslCertificate
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        WebACLId: !Ref pSdsHomePage
      Tags:
        - Key: component
          Value: cdn

  SdsHomePageCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Comment: !Sub CF Cache Policy for the SDS-home-page site ${pEnvironment}
        DefaultTTL: 300
        MaxTTL: 86400
        MinTTL: 1
        Name: !Sub
          - "SdsHomePage-${pComponent}-cache-Policy-${ResourceName}"
          - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: whitelist
            QueryStrings:
              - cb
