dist: trusty
sudo: required
language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
  - maintenance-1.1
before_install:
- mkdir -p ~/.m2; wget -q -O ~/.m2/settings.xml https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_maven_settings_simple.xml
- sudo mkdir -p /data/lucene; sudo wget -O /data/lucene/namematching-20210811-3.tgz https://archives.ala.org.au/archives/nameindexes/20210811-3/namematching-20210811-3.tgz
- cd /data/lucene
- sudo tar zxvf namematching-20210811-3.tgz
- sudo ln -s namematching-20210811-3 namematching
- ls -laF
- sudo mkdir -p /data/sds
- sudo wget -O /data/sds/sds-test-config.tgz https://archives.ala.org.au/archives/test/sds-test-config.tgz
- cd /data/sds
- sudo tar xvzf sds-test-config.tgz
- cd $TRAVIS_BUILD_DIR
- echo TRAVIS_PULL_REQUEST = ${TRAVIS_PULL_REQUEST}
script:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then mvn -P travis clean install deploy;
  else mvn -P travis clean install; fi
env:
  global:
  - secure: "i98laiss9bNgDs9bqC3gjCjgRLL1GnHU3bvcJe1XRnOcdy3Hj5ocElH4zXmg7n0rqTyOVEhj5R5Ech4I1DAY793i/pqurffZhLh4iM48LbNHXcTZwxYG8jP5EqTmxDemryLqsdHrrGSQdK1N0KjCAoZcWQ7PyM4zRS8ALWelmBI2hq5aaT1CrAMNNm/VrutgDe5YMzLBnE3BtjV0nDeed2P2Xucb9shDo5svOfKTsWlJ/DKp7v6vddHFUsSz4n1XTkJva24Mjrr/801NO37emcEDH9BrrzL3yeEFXu5acJxsnAWX14coIh3y9knYLBCARY991QY86sa3oVT8vdMBU1FIGigACPMTbF/ZQ7RkDIBK6sKAF5ClXAyTlb7glj/8UN1RDbvUNvKiYX0BYpsi/8mGZ4FiwEO87c5cVykMWD19UQHhsUZHTrmT6WDl8EvUqYLqpmIhJWRuywbN6b0LpVLdTQJXZjzu+Vff3AemTGZU50+znhDxKepdselDB60dsOylzEOKHVtZ22+3xM6dpkuHJY61lkGj2lh+RPzugF0B7tIBz+LFMr+KVT5amyQNIY+2ddU/gmdkTIn7RkSAAwgN0AW+ZOooPmDnn19XN27/oIs90luSGLbYn4zO13++QCpUutBIb37rUGoi/CS86LRMnMeTFtHlCZuMEcJKabM="
  - secure: "FgDIMt6meka/ENaSOLqEOvSL+SXd9so95dDDg6ozM/ePum/OlxOrQPytKWORaTuDw/xWeLpkL+Hc6OhL2w/3KM68yQYUu79MFzKA8gNO+Xl7Fw6Czw0FalavEqoAOxYlRWAs+frcDi5/2W85KhDCDapxR0WIg4oFwKyimDmebPHDoTKt05FQpA5OJnAjkxWyli5fWCWJNk464AkCWwuateUkeYodXwpoBWSNia//dwP5l3fnqcpj7X8eBreqYa7hkKuo7VYeN46JeKmUVyIAWG9+YlVsk2oqBoEIgcs6DLljgO8sC/hNUytSZDSjzeJTO4/BMOJ7NxRL3v3koGyhGbMZUBffjjDf5lTgnLq1v9/DVe8MKhk31p7SqUkAJ1xnDJyAWy0iDMWRo4vZ5eBBUYz1Selqf+PY84X8+QHX5LnlTvbTvgXdyx84zXkquviRJV2oguaMdcZgWYgDjzMg1yYD1vgtwA0diV+cnbcnxCf0eQH3MM+Jr3z2+4qKdq5sm7ThTb7Seb7GLBfmd3lfDdNiHV37ktl2gN87HGYYfmojXXnc7wWarbDTujI3jy5yUoixl/zND3wUCknjP7P/f8jBoczD/nvlkDV4DXFTTIt73SZUzL9IdtDr5zT6Ezxuech1/IvpkHL2uLlA+kncYs3Cl+VVXE94E7GxcZFVDs4="
  
