dist: trusty
sudo: required
language: java
jdk:
- openjdk8
branches:
  only:
  - master
  - develop
before_install:
- mkdir -p ~/.m2; wget -q -O ~/.m2/settings.xml https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_maven_settings_simple.xml
- sudo mkdir -p /data/lucene; sudo wget -O /data/lucene/namematching-20200214.tgz https://archives.ala.org.au/archives/nameindexes/20200214/namematching-20200214.tgz
- cd /data/lucene
- sudo tar zxvf namematching-20200214.tgz
- sudo ln -s namematching-20200214 namematching
- ls -laF
- sudo mkdir -p /data/sds
- sudo wget -O /data/sds/sds-test-config.tgz https://archives.ala.org.au/archives/test/sds-test-config.tgz
- cd /data/sds
- sudo tar xvzf sds-test-config.tgz
- cd $TRAVIS_BUILD_DIR
- echo TRAVIS_PULL_REQUEST = ${TRAVIS_PULL_REQUEST}
script:
- 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then mvn -P travis clean install deploy; else mvn -P travis clean install; fi'
env:
  global:
  - secure: "BuIjgXY9lGlC1/WhW3Ic6+2V3ZgOU1aE1nEwcZ2FcJcroYMbOHgzhk7snsqTRekwmiRkqyBkvVVTeXp+j9Z2LuhMKN4A3S5LXCbC/7oOXZHvS/m03rV3qlkOTTPLG/wpTIBiBX35gG2EMpsv9RynJ95nRDH8qL2EdTPMhPa24UREcB3hB+47ecV9cU8jRduyjhm3rQDXUr9/t/bRQzwh3YK6ONlebSZSXecw4eCdlV0qjkOLEk9Lk6ZpPri94kscsqcfitnQ9Xr704PmarJEVhRerl5k/Lzx5feUWBGIegi9QWqmS+5i/LuxNq4kza8S3c+qEe3mfnaga9t6Y7EQClUV4VHPfA97fh6cPxyyI/tLn5mXe0RFyY7mYRzPgB4G/ZMfKjPt/flSKSsDjsywIGz1w7P+a4hsZrbg0ty+1rgYseUAI0+EhT8oQNAU6d6UHd/UHTZw624DdPbiC/C2EdTJyGuy2ibwhHWG09fWBcbI5ybaT20xypjITjBXgTUeXAQRZKwqz//qI99zFVyQOTlEU83XS6fmVW8zLek4mSKsEIzLJpflP1p6vMhRQjEtHaOBtTKfgJsHJ6aUCQ/X2LW4Rdrq9FtnZFqCCzBr3hmyNSaoIkdLwPC3lkv2kOuvYJ3o8X+NS95GZAW+yQhvUqZVFHOoaLhz6fJAZKzrl0E="
  - secure: "OoBEvbLSyjpFTN7HZX0UlHSpK1yAkmbHwEzoYeL3W9WgnAVx3IoEY5DmKOsyCW/6Zm8TUcC0rrGH0uCbhpq6TcWg1Zo3AvcsWdr7QOgt1WEx1AFx9lhj4FT/fJ1QzHINV9cLnYIFEIxkN+Yb6saFjOytX7M1DvYwn8xrXBWPqh059tXLNMmnVdrMHmt+8wkKW5G8iXLINQK8Ylr/U0ytjfTJIZQrCZPXzsN8Xjq9dpZaRONKm9kiD9Yc4TOX9G0FiRPyOoZzuv7XNasn2DadOJZ2gLwjTsW6GxdU90/HxB75SaSLCDFofB8ZxgVEbfYtEzMsCyX1FzQSvCZvuqiJ/bjLLRlSJwRPd/HRxhT/5vwX+zAbJYMxT6sOm1q2BbAKQOfvutoe7/JWPQJ/hraSz9FEbBwef509OIUI98g67ecB5XsN0fhzVFnXko6MhFhziOKKCGc3EutLV2fxPUcG1B9AJcGLasZDE0CkltEXvP11WiO7SsJSeiy6uj3OMgvvwqwgU/0CAWT4Xs1g7oZztFdQoMYIHRT6qy7C2OHOk7BVzCxFlw+SkaG/03Vwc7YRcEXedmqbcL7Qtieilg29Pw9+3Rnm1zGxpKYBLozGa2QUZFSe2qrQZu9XZQlLeYaASRjsIGKvuWVEdfr/E0Eir8sCISwUqk2Qlb5qG0TOzUo="
