arch: amd64
os: linux
dist: jammy
sudo: required
language: java
jdk:
- openjdk11
branches:
  only:
  - master
  - develop
before_install:
- mkdir -p ~/.m2; wget -q -O ~/.m2/settings.xml https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_maven_settings_simple.xml
- sudo mkdir -p /data/lucene; sudo wget -O /data/lucene/namematching-20210811-3.tgz
  https://archives.ala.org.au/archives/nameindexes/20210811-3/namematching-20210811-3.tgz
- cd /data/lucene
- sudo tar zxvf namematching-20210811-3.tgz
- sudo ln -s namematching-20210811-3 namematching
- ls -laF
- sudo mkdir -p /data/sds
- sudo wget -O /data/sds/sds-test-config.tgz https://archives.ala.org.au/archives/test/sds-test-config.tgz
- cd /data/sds
- sudo tar xvzf sds-test-config.tgz
- cd $TRAVIS_BUILD_DIR
- echo TRAVIS_PULL_REQUEST = ${TRAVIS_PULL_REQUEST}
script:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then mvn -P travis clean install deploy;
  else mvn -P travis clean install; fi
env:
  global:
  - secure: X0XB8WFY8qu7oF8wnniEU8ihb+uPb2U+0kySBl5qWQXWO8kRjWjpp53lHP4Fr8fgtybpuHKaH2Q+3hgvpZtunM7+kxTgSEHRxFhqKJYs4VgddHw+HkGEsmn0IVTyS7cDiAHoEFIlq/+pCe6ONioeE4ZYtYcXp5ylVClU1IVIeUwwWfDMX18xbfLaZD/tOEVLiDsWvLx7R1/PFopVmkbPS93T9qJZIxGmcfry1S6boykPXQsSqKVg3w7mo7pWwFeGVasrHKNLXjzVSRRafQWFjEvWkTn1hP76mxlMOKGKcUHObjSQdYSOT7f9FMA7if/xYQKzjvDtmkqjwtcA1Rxt/M/3XytZnW4FsFkN9/OpucDK0QsGC0uEdpO+SXo93ay/JYJfvfahO8QmlUcM6hVgz4zl1NoSbjKxLGI6XEC/LdXMP1I5/r+VgQasqc8UAsBIKHyB7C+GjtPP91VjS+wSOK3lUyDqKv7p+5Ieyj+Td6uVr9oJVZc4yJNuqpooYVUGVu78+36IR+ppb7124p/P8PsVD+vF3x8XWOQBTSrd1z72BER3/nuuTz1WHzkZMIN/6FzF2WMbie5rj1TklBarPdfELQGCJODT230hj0YhBcEnDycguFkP9iN214udSMhUWfyN9tdmrqV6nAnYeta2HEZ05m3qbCe6xP6uswxZLRY=
  - secure: XAx7YydSxXjIFCNoJ+pZbLeBKtFlWo1fkHrJXFe3gdHRd4NEuTkPyss1nvDzTIZ41TXRvI4TpgphYM7W/GVx9Wti+rArwILiYuPcDXkGxM4/e7oelHKOAirYNKkYIfjV4iMcex5vju3dKd2KH6N2qY1aVkAKmKpkIcM9Lbskf5T8DcTvCVKcQvWmhKgWl7ky3+csi2mvJ5Q2pBfpnmBSsBoQlcZsImLzyiJP0qLODpZc92jRpGDVYPIrEw3DnuyBHE21CkKiBawDH9JyNQCxSHpYjGM59FAFWo7X7TIRV8a8tCZtioEquIGlFl5giqqwrP/Q5A5pXCrSz2IlFhHyqkLC5jRIvhHIenyKCUYdfu21m/nquUrYQzWhE3MEuzpCU5eMznn3h628jtbTq/QjdJw92RnMYkYwNac0/Dm7bQUATfcc9tti/gGZGhZCBVYLMJkouPhrL/0wtTLa7QHBCxzehRfPXuvZRJATk4K+rGP4Lk3YL1dCFoXzRV44u2meQom5Lpgo4tn7Jgd3WRjHP0IDp5sYpWyL2evTN3VW0FEppFEPybs0uoCrF0Cs+P2pwr+IrufVQfJPmmHbieHfac3qUTa1SgzRUuvRcM9ggjX3vnFwZJWCeQtD5PHpZeHjlhQStP3BMzvFL9i2M0kzWUWccXLDxLMmDdC4aeXGQr8=
