dist: trusty
sudo: required
language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
before_install:
- mkdir -p ~/.m2; wget -q -O ~/.m2/settings.xml https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_maven_settings_simple.xml
- sudo mkdir -p /data/lucene; sudo wget -O /data/lucene/namematching-20200214.tgz https://archives.ala.org.au/archives/nameindexes/20200214/namematching-20200214.tgz
- cd /data/lucene
- sudo tar zxvf namematching-20200214.tgz
- sudo ln -s namematching-20200214 namematching
- ls -laF
- sudo mkdir -p /data/sds
- sudo wget -O /data/sds/sds-test-config.tgz https://archives.ala.org.au/archives/test/sds-test-config.tgz
- cd /data/sds
- sudo tar xvzf sds-test-config.tgz
- cd $TRAVIS_BUILD_DIR
- echo TRAVIS_PULL_REQUEST = ${TRAVIS_PULL_REQUEST}
script:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && mvn -P travis clean install deploy || mvn -P travis clean install'
env:
  global:
  - secure: qhW/upWDYH/QjOvSLE6rp9wfnGQwgBIt3IXLLRRREbtMJiBdn9eNpzgsTc+z9yljDd1de5gtfM7D1yCk1eaXqXF9E+HzuE45YFDfE5ifKwNOU9I+8b6KC9QMMUeI7mxK1mCRtlTY36G08tS5djFkKBx/m7PbTtd9PAyfqUt261OzxYx9eTW8qLI+W47p4w6t6d9kjxXuRarDN6ESTNAcWvW7b7SZ1qiH3yKedBIL+FMJ8ms4U9RhHKosPv8bLUUgvtcTbZLJ7nqqM8+9zeHQO1Otp4D+j26FFvxpNq0LGBPLpBc3M/kVqNxc52G7kFYUmb3Y0I6uW+aj50tvI6Qr5JU9g920NiLNJ84VbdJKVJsFdC8flz9W9G0y5OLCMnobJTCw7woFYLZ/mFyopMl/zrc+YI0Dd3MRw5ePlkPMrQgj6vDsqdHOgrayD5b3AUo6p59wtNYuVfcgmOfxy+MwZlvcO6S0OMfav6HuFW40yc5LrbVvnvNobm0eVcTY9JNAkCl2w+9CJR5gKw4s24+V4HbZZdTjpm9CyEHjb94gA4/0/SB9B4aukC5mdJqRotPS1N9ZEDzlJ6dMtyrVcIizznIayqScNvQqSKQXmfPxhcIo8l/nfUoKz0xgp9jzxlq5ywGdCyn4ihqHOra0vz0ssoYMWY6mxvtUHHpGW4HMwsM=
  - secure: cWJbEG7V9D9fQ+rAq6UFpf0ItF4WDUvAwq5+BJjUNUcK7G+cUz1xa9nZCJe588NusUwngHubL4bID54CQGdyABYhdEasXu24GfCa4EHeOSEZw3nwSCkkxbKPkedgTwtas83wqj8PvKKglSXo+C3YwwcuSDJj6g7vtvJJYa0lTPJ9BqsIU07JecR33i974LYmZWW+zpiw7OZzlev8U+mIRMWu2LSjexZ41jYu50Qazo4UkNCaCx3QQ+2YJMPGg0aAXD0FZjWyXhDp5ZlOQG4Nc/oXAZrhegv+NPNIS6XkvNxgWkpcQGhb5Tvv8vg3MIiHVkTsROV6o2ZUjdadOE++dSlcB9k8mhgQOJ2yc1q5MTiuVzm4zWXe/dpcnU8UNHMhjHtbLfynzPN2g/cPreZUOSIQCXG2Vra56B6UFxgPxgM7OGPYILMIswSPgKaAS3CBNjfELksiex+d7qDyEPRzcJYfAPS3NXShRybE9shzLeHRwwNjrHU2KAgRv3b/esELTWqGOZQFqOtC7HbJwRyRXbfvJSPCYIU2GHVjQQeSEcrRuJjsZNgYYJ02b0O9PnrXQMN80amnzmffc3MxB7ICpnxJkHsfzlXJ3GoLgcjT40QMwSqK+NrSMfarSV4V/t/S0bMudE3Jgt2UEzkW30MlYsO+gxOW3wEiZMFlt+PBn6c=
