logging:
  level: INFO
  loggers:
    au.org.ala: WARN
server:
  applicationConnectors:
    - type: http
      port: 9189
      outputBufferSize: 32KiB
      idleTimeout: 30 seconds
      minBufferPoolSize: 64 bytes
      bufferPoolIncrement: 1KiB
      maxBufferPoolSize: 64KiB
      acceptorThreads: 1
      selectorThreads: 2
      acceptQueueSize: 1024
      reuseAddress: true
  adminConnectors:
    - type: http
      port: 9190
conservation:
  index: /data/lucene/namematching-20200214
  speciesUrl: file:///data/sds/sensitive-species-data.xml
  zonesUrl: file:///data/sds/sensitivity-zones.xml
  categoriesUrl: file:///data/sds/sensitivity-categories.xml
  layersUrl: file:///data/sds/layers.json
  layersServiceUrl: https://spatial.ala.org.au/layers-service
  cache:
    entryCapacity: 10000
    enableJmx: true
  generalisations:
    - action: retain
      field: dwc:informationWithheld
    - action: retain
      field: dwc:dataGeneralizations
    - action: latLong
      latitudeField: dwc:decimalLatitude
      longitudeField: dwc:decimalLongitude
    - action: clear
      field: dwc:verbatimLatitude
    - action: clear
      field: dwc:verbatimLongitude
    - action: clear
      field: dwc:verbatimCoordinates
    - action: clear
      field: dwc:locality
    - action: clear
      field: dwc:verbatimLocality
    - action: retain
      field: dwc:municipality
    - action: retain
      field: dwc:stateProvince
    - action: retain
      field: dwc:country
    - action: clear
      field: dwc:locationRemarks
    - action: clear
      field: gridReference
    - action: clear
      field: footprintWKT
    - action: add
      field: dwc:coordinateUncertaintyInMeters
      retainUnparsable: false
      useSensitivity: true
      add: 0
    - action: add
      field: generalisationToApplyInMetres
      retainUnparsable: false
      useSensitivity: true
      add: 0
    - action: add
      field: generalisationInMetres
      retainUnparsable: false
      useSensitivity: true
      add: 0
    - action: clear
      field: northing
    - action: clear
      field: easting
    - action: clear
      field: bbox
    - action: clear
      field: dwc:eventID
    - action: clear
      field: dwc:eventDate
    - action: clear
      field: dwc:eventTime
    - action: clear
      field: eventDateEnd
    - action: clear
      field: dwc:verbatimEventDate
    - action: clear
      field: dwc:day
    - action: clear
      field: dwc:month
    - action: retain
      field: dwc:year
    - action: retain
      field: dwc:scientificName
    - action: retain
      field: dwc:family
    - action: retain
      field: dwc:genus
    - action: retain
      field: dwc:specificEpithet
    - action: retain
      field: dwc:infraspecificEpithet
    - action: retain
      field: intraspecificEpithet

