AWSTemplateFormatVersion: '2010-09-09'
Description: SDS Home Page frontend Infrastructure

Parameters:
  pHomePageBucketPath:
    Type: String
    Description: path that the SDS frontend files are stored under
  pHomePageSubDomain:
    Type: String
    Description: The subdomain SDS frontend is accessed on
  pSdsHomePageWebAclArn:
    Type: String
    Description: The WAF Web ACL to attach the CloudFront distribution to
  pCleanBranch:
    Type: String
    Description: A cleaned version of the code branch name
    Default: development
  pXmlBucketPath:
    Type: String
    Description: path that the SDS xml files are stored under
  pXmlSubDomain:
    Type: String
    Description: The subdomain the SDS xml file is accessed on
  pEnvironment:
    Type: String
    Description: The AWS environment this belongs to
  pHostedZone:
    Type: String
    Description: The hosted zone the site are accessed under
  pProductName:
    Type: String
    Description: The product name
  pSourceBucket:
    Type: String
    Description: The bucket name for the site
  pSslCertificate:
    Type: String
    Description: The arn of the SSL certificate to be used

Conditions:
  IsDev: !Equals
    - !Ref pEnvironment
    - development
  NotDev: !Not [ Condition: IsDev ]

Resources:
  SdsHomePageBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub ${pSourceBucket}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE
      Tags:
        - Key: component
          Value: website
        - Key: Name
          Value: !Sub ${pSourceBucket}

  SdsHomePageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SdsHomePageBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${SdsHomePageBucket}/*'
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${SdsHomePageCloudFrontOai}'

  SdsHomePageCloudFrontOai:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub CF Origin Access Identity for ${pProductName} ${pEnvironment}

  SdsCloudFrontDistro:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        pSubDomain : !Ref pHomePageSubDomain
        pHostedZone : !Ref pHostedZone
        pEnvironment : !Ref pEnvironment
        pBucketPath : !Ref pHomePageBucketPath
        pSourceBucket : !Ref pSourceBucket
        pSslCertificate : !Ref pSslCertificate
        pSdsHomePageCloudFrontOai : !Ref SdsHomePageCloudFrontOai
        pSdsHomePageWebAclArn : !Ref pSdsHomePageWebAclArn
        pComponent : sds
      TemplateURL: cloudfront_distro.yaml
      Tags:
        - Key: product
          Value: !Ref pProductName
        - Key: component
          Value: sds
        - Key: environment
          Value: !Ref pEnvironment
        - Key: Name
          Value: SDS home page
      TimeoutInMinutes: 15

  # RegionsCloudFrontDistro:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     Parameters:
  #       pSubDomain : !Ref pRegionsSubDomain
  #       pHostedZone : !Ref pHostedZone
  #       pEnvironment : !Ref pEnvironment
  #       pBucketPath : !Ref pRegionsBucketPath
  #       pSourceBucket : !Ref pSourceBucket
  #       pSslCertificate : !Ref pSslCertificate
  #       pSdsHomePageCloudFrontOai : !Ref SdsHomePageCloudFrontOai
  #       pSdsHomePage : !Ref pSdsHomePage
  #       pComponent : regions
  #     TemplateURL: cloudfront_distro.yaml
  #     Tags:
  #       - Key: product
  #         Value: !Ref pProductName
  #       - Key: component
  #         Value: regions
  #       - Key: environment
  #         Value: !Ref pEnvironment
  #       - Key: Name
  #         Value: Atlas-index Regions
      # TimeoutInMinutes: 15

  # AdminCloudFrontDistro:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     Parameters:
  #       pSubDomain : !Ref pAdminSubDomain
  #       pHostedZone : !Ref pHostedZone
  #       pEnvironment : !Ref pEnvironment
  #       pBucketPath : !Ref pAdminBucketPath
  #       pSourceBucket : !Ref pSourceBucket
  #       pSslCertificate : !Ref pSslCertificate
  #       pSdsHomePageCloudFrontOai : !Ref SdsHomePageCloudFrontOai
  #       pSdsHomePage : !Ref pSdsHomePage
  #       pComponent : admin
  #     TemplateURL: cloudfront_distro.yaml
  #     Tags:
  #       - Key: product
  #         Value: !Ref pProductName
  #       - Key: component
  #         Value: admin
  #       - Key: environment
  #         Value: !Ref pEnvironment
  #       - Key: Name
  #         Value: Atlas-index Admin
      TimeoutInMinutes: 15


Outputs:
  SdsHomePageBucketName:
    Value: !Ref SdsHomePageBucket
  SdsHomePageBucketArn:
    Value: !GetAtt SdsHomePageBucket.Arn
