AWSTemplateFormatVersion: '2010-09-09'
Description: SDS Home Page frontend Infrastructure

Parameters:
  pCleanBranch:
    Type: String
    Description: A cleaned version of the code branch name
    Default: development
  pEnvironment:
    Type: String
    Description: The AWS environment this belongs to
  pHomePageBucketPath:
    Type: String
    Description: path that the SDS frontend files are stored under
  pHomePageOldSubDomain:
    Type: String
    Description: The old subdomain, aliased to the CF distribution
  pHomePageSubDomain:
    Type: String
    Description: The subdomain SDS frontend is accessed on
  pHostedZone:
    Type: String
    Description: The hosted zone the site are accessed under
  pProductComponent:
    Type: String
    Description: The product component
  pProductName:
    Type: String
    Description: The product name
  pSourceBucket:
    Type: String
    Description: The bucket name for the site
  pSslCertificate:
    Type: String
    Description: The arn of the SSL certificate to be used
  pXmlBucketPath:
    Type: String
    Description: path that the SDS xml files are stored under
  pXmlFileBucketName:
    Type: String
    Description: The S3 bucket name for other files/assets.
  pXmlFilePathPattern:
    Type: String
    Description: The CloudFront path pattern to route to the other files bucket (e.g., /other-assets/*).
  pXmlFileS3KeyPrefix:
    Type: String
    Description: The key prefix (folder) in the other files S3 bucket.
    Default: "other-assets"

Conditions:
  IsDev: !Equals
    - !Ref pEnvironment
    - development
  NotDev: !Not [ Condition: IsDev ]

Resources:

  SdsHomePageBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub ${pSourceBucket}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE
      Tags:
        - Key: component
          Value: website
        - Key: Name
          Value: !Sub ${pSourceBucket}

  SdsHomePageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SdsHomePageBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${SdsHomePageBucket}/*'
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${SdsHomePageCloudFrontOai}'

  SdsXmlFileCloudFrontOai:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub CF Origin Access Identity for ${pProductName} ${pEnvironment} Other Files

  SdsXmlFileBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref pXmlFileBucketName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${pXmlFileBucketName}/*'
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${SdsXmlFileCloudFrontOai}'

  SdsHomePageCloudFrontOai:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub CF Origin Access Identity for ${pProductName} ${pEnvironment}

  SdsHomePageDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub '${pHomePageSubDomain}.${pHostedZone}'
      Comment: !Sub ${pProductComponent} domain for the ${pEnvironment} environment
      Type: A
      AliasTarget:
        DNSName: !GetAtt SdsHomePageCloudFrontDistro.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneName: !Sub '${pHostedZone}.'

  SdsHomePageOldDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub '${pHomePageOldSubDomain}.${pHostedZone}'
      Comment: !Sub Old ${pProductComponent} domain for the ${pEnvironment} environment
      Type: A
      AliasTarget:
        DNSName: !GetAtt SdsHomePageCloudFrontDistro.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneName: !Sub '${pHostedZone}.'

  SdsHomePageCloudFrontDistro:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub '${pHomePageSubDomain}.${pHostedZone}'
          - !Sub '${pHomePageOldSubDomain}.${pHostedZone}'
        Comment: !Sub CF Distribution for SDS-home-page ${pProductComponent} ${pEnvironment}
        CustomErrorResponses:
          - ErrorCode: 403
            ErrorCachingMinTTL: 300
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: !Ref SdsHomePageCachePolicy
          Compress: true
          TargetOriginId: sds-index-s3
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: false
        Origins:
          - DomainName: !Sub '${pSourceBucket}.s3.${AWS::Region}.amazonaws.com'
            Id: sds-index-s3
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${SdsHomePageCloudFrontOai}'
            OriginPath: !Sub '/${pHomePageBucketPath}' # e.g., /development/sds-home-page
          - DomainName: !Sub '${pXmlFileBucketName}.s3.${AWS::Region}.amazonaws.com' # Reference the existing bucket name
            Id: sds-xml-file-s3 # Unique ID for this new origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${SdsXmlFileCloudFrontOai}'
            OriginPath: !Sub '/${pXmlFileS3KeyPrefix}' # e.g., /other-assets
        ViewerCertificate:
          AcmCertificateArn: !Ref pSslCertificate
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        CacheBehaviors: # Add this section for path-based routing
          - PathPattern: !Ref pXmlFilePathPattern # e.g., /other-assets/* or /specific-file.pdf
            TargetOriginId: sds-xml-file-s3 # Must match the Id of the new origin
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            CachePolicyId: !Ref SdsHomePageCachePolicy # You might want a different cache policy
            Compress: true
            ViewerProtocolPolicy: redirect-to-https
      Tags:
        - Key: component
          Value: cdn

  SdsHomePageCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Comment: !Sub CF Cache Policy for the SDS-home-page site ${pEnvironment}
        DefaultTTL: 300
        MaxTTL: 86400
        MinTTL: 1
        Name: !Sub
          - "SdsHomePage-${pProductComponent}-cache-Policy-${ResourceName}"
          - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: whitelist
            QueryStrings:
              - cb



Outputs:
  SdsHomePageBucketName:
    Value: !Ref SdsHomePageBucket
  SdsHomePageBucketArn:
    Value: !GetAtt SdsHomePageBucket.Arn
